- hosts: nodes
  tasks: 
  - name: get admin password
    command: cat /var/lib/jenkins/secrets/initialAdminPassword
    register: adminPassword

  - name: Debug
    debug:
      msg: "{{adminPassword.stdout}}"

  - name: Get Jenkins crumb
    uri:
      user: admin
      password: "{{ adminPassword.stdout }}"
      force_basic_auth: yes
      url: "http://localhost:8080/crumbIssuer/api/json"
      return_content: yes
    register: jenkins_crumb
    until: jenkins_crumb.content.find('Please wait while Jenkins is getting ready to work') == -1
    retries: 10
    delay: 5



  - name: Set crumb token
    set_fact:
      jenkins_crumb_token: "{{ jenkins_crumb.json.crumbRequestField }}={{ jenkins_crumb.json.crumb }}"

  - name: ad
    debug:
      msg: "{{jenkins_crumb.json.crumb}}"


  #- name: ssh
  #  shell: ssh-keygen -b 4096 -C "bhushan.crysis@gmail.com" -t rsa -f /vagrant/.ssh/id_rsa -q -N ""
  #  args:
  #    creates: /vagrant/.ssh/id_rsa


  - name: Get list of jobs
    uri:
      user: admin
      password: "{{adminPassword.stdout}}"
      force_basic_auth: yes
      url: "http://127.0.0.1:8080/api/json?tree=jobs[name]"
      return_content: yes
    register: jenkins_jobs
    until: jenkins_jobs.content.find('Please wait while Jenkins is getting ready to work') == -1
    retries: 10
    delay: 5

  - name: Check if seed job exists
    set_fact:
      jenkins_seed_job_exists: "{{ 'checkbox.io' in (jenkins_jobs.content|from_json).jobs|map(attribute='name')|list }}"

  - name: Create seed job
    uri:
      user: admin
      password: "{{adminPassword.stdout}}"
      force_basic_auth: yes
      url: "http://127.0.0.1:8080/createItem?name=checkbox.io&{{ jenkins_crumb_token }}"
      method: POST
      headers:
        Content-Type: application/xml
      body: "{{ lookup('file','config.xml') }}"
    register: jenkins_seed_job_updated
    when: not jenkins_seed_job_exists


  - name: Run seed job
    uri:
      user: admin
      password: "{{adminPassword.stdout}}"
      force_basic_auth: yes
      url: "http://127.0.0.1:8080/job/checkbox.io/build"
      method: POST
      headers:
        Jenkins-Crumb : "{{ jenkins_crumb.json.crumb }}"
      status_code: 201







